global using ActiveDirectoryToRestApi.Configurations;
global using ActiveDirectoryToRestApi.Extensions;
global using ActiveDirectoryToRestApi.Models;
global using ActiveDirectoryToRestApi.Services;
global using Microsoft.AspNetCore.Mvc;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.DirectoryServices.Protocols;
global using System.Net;
